{
    "Service": "/sampleapp/Services/com_sap_edm_sampleservice_v4.service",
    "DefiningRequests": [{
            "Name": "Customers",
            "Query": "Customers"
        },
        {
            "Name": "Products",
            "Query": "Products"
        },
        {
            "Name": "SalesOrderHeaders",
            "Query": "SalesOrderHeaders"
        },
        {
            "Name": "SalesOrderItems",
            "Query": "SalesOrderItems"
        }
    ],
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText": "$(L,Action_Init_Activity)",
    "ActionResult": {
        "_Name": "init"
    },
    "OnFailure": "/sampleapp/Actions/com_sap_edm_sampleservice_v4/Service/InitializeOfflineFailureMessage.action",
    "OnSuccess": "/sampleapp/Actions/com_sap_edm_sampleservice_v4/Service/InitializeOfflineSuccessMessage.action"
}