{
    "_Type": "Action.Type.BannerMessage",
    "Message": "$(L,Action_ErrorArchive_Upload_Failed)",
    "Duration": 0,
    "Animated": false,
    "OnActionLabelPress": "/sampleapp/Actions/ErrorArchive/NavToErrorArchive_List.action",
    "ActionLabel": "$(L,Action_ErrorArchive_View_Errors)"
}